import { LostFoundItem } from "./types";

export const initialItems: LostFoundItem[] = [
  {
    id: "1",
    title: "MacBook Pro 14-inch",
    description: "Silver MacBook Pro with stickers on the cover. Left it at the library study room 3B.",
    category: "Electronics",
    status: "lost",
    location: "Main Library, Study Room 3B",
    date: "2026-01-02",
    contactEmail: "alex.johnson@university.edu",
    contactName: "Alex Johnson",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=300&fit=crop",
    isResolved: false,
    createdAt: "2026-01-02T10:30:00Z",
  },
  {
    id: "2",
    title: "Blue Hydroflask Water Bottle",
    description: "Found this water bottle at the gym. Has some scratches and a campus logo sticker.",
    category: "Accessories",
    status: "found",
    location: "Recreation Center, Weight Room",
    date: "2026-01-02",
    contactEmail: "maria.santos@university.edu",
    contactName: "Maria Santos",
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=300&fit=crop",
    isResolved: false,
    createdAt: "2026-01-02T14:15:00Z",
  },
  {
    id: "3",
    title: "Student ID Card - Michael Chen",
    description: "Found a student ID card near the cafeteria entrance. Name visible on card.",
    category: "ID & Cards",
    status: "found",
    location: "Student Center Cafeteria",
    date: "2026-01-01",
    contactEmail: "sarah.kim@university.edu",
    contactName: "Sarah Kim",
    imageUrl: "https://images.unsplash.com/photo-1578670812003-60745e2c2ea9?w=400&h=300&fit=crop",
    isResolved: true,
    createdAt: "2026-01-01T12:00:00Z",
  },
  {
    id: "4",
    title: "Black North Face Backpack",
    description: "Lost my black backpack with textbooks inside. Has a keychain attached to the zipper.",
    category: "Bags",
    status: "lost",
    location: "Engineering Building, Room 204",
    date: "2026-01-01",
    contactEmail: "james.wilson@university.edu",
    contactName: "James Wilson",
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop",
    isResolved: false,
    createdAt: "2026-01-01T09:45:00Z",
  },
  {
    id: "5",
    title: "AirPods Pro Case",
    description: "White AirPods Pro case found on a bench. Has initials 'JR' engraved.",
    category: "Electronics",
    status: "found",
    location: "Quad Area, Near Fountain",
    date: "2025-12-31",
    contactEmail: "emily.davis@university.edu",
    contactName: "Emily Davis",
    imageUrl: "https://images.unsplash.com/photo-1603351154351-5e2d0600bb77?w=400&h=300&fit=crop",
    isResolved: false,
    createdAt: "2025-12-31T16:20:00Z",
  },
  {
    id: "6",
    title: "Car Keys with Honda Fob",
    description: "Found a set of car keys with a Honda key fob and a small teddy bear keychain.",
    category: "Keys",
    status: "found",
    location: "Parking Lot B",
    date: "2025-12-30",
    contactEmail: "david.lee@university.edu",
    contactName: "David Lee",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    isResolved: true,
    createdAt: "2025-12-30T11:30:00Z",
  },
  {
    id: "7",
    title: "Calculus Textbook",
    description: "Lost my Calculus 2 textbook. Has my name written inside the cover.",
    category: "Books",
    status: "lost",
    location: "Math Building, Lecture Hall A",
    date: "2025-12-30",
    contactEmail: "rachel.green@university.edu",
    contactName: "Rachel Green",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop",
    isResolved: false,
    createdAt: "2025-12-30T08:00:00Z",
  },
  {
    id: "8",
    title: "Prescription Glasses",
    description: "Found black-framed prescription glasses in a hard case near the bus stop.",
    category: "Accessories",
    status: "found",
    location: "Campus Bus Stop A",
    date: "2025-12-29",
    contactEmail: "tom.harris@university.edu",
    contactName: "Tom Harris",
    imageUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=300&fit=crop",
    isResolved: false,
    createdAt: "2025-12-29T17:45:00Z",
  },
];
